### ISSUE TITLE
MountVolume.MountDevice failed for volume "<VOLUME>"  : rpc error: code = Unavailable desc = grpc: the connection is unavailable

### ISSUE THREAD

**Issue by lohazo** [digitalocean/csi-digitalocean#54] opened 2018-08-14 03:06 UTC
Kubernetes `1.10.5` running on `CoreOS` install by `rke`. 
I follow step in https://github.com/digitalocean/csi-digitalocean
and result: 

![1____downloads_terraform__zsh_](https://user-images.githubusercontent.com/6048013/44069542-79f42944-9fa9-11e8-8461-ec52499de4cc.png)

Some information:
![1____downloads_terraform__zsh_](https://user-images.githubusercontent.com/6048013/44069092-754f60c2-9fa7-11e8-9084-cfce2245c9fc.png)

![1____downloads_terraform__zsh_](https://user-images.githubusercontent.com/6048013/44069139-a8addb60-9fa7-11e8-9ce0-70e6588d9c01.png)

![1____downloads_terraform__zsh_](https://user-images.githubusercontent.com/6048013/44069160-bd110618-9fa7-11e8-99ee-731465af9122.png)

![1____downloads_terraform__zsh_](https://user-images.githubusercontent.com/6048013/44069210-e82bd0f8-9fa7-11e8-8a5d-70ffb9bbd808.png)

**Comment by lohazo** [comment] 2018-08-14 03:06
@fatih I just open a new issue here

**Comment by fatih** [comment] 2018-08-22 08:20
@lohazo can you please provide example PVC and POD manifests so I can try them out. What exactly did you created?

**Comment by lohazo** [comment] 2018-08-22 10:27
I follow step in: https://github.com/digitalocean/csi-digitalocean
PVC:
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: do-block-storage

POD:
kind: Pod
apiVersion: v1
metadata:
  name: my-csi-app
spec:
  containers:
    - name: my-frontend
      image: busybox
      volumeMounts:
      - mountPath: "/data"
        name: my-do-volume
      command: [ "sleep", "1000000" ]
  volumes:
    - name: my-do-volume
      persistentVolumeClaim:
        claimName: csi-pvc

**Comment by peterver** [comment] 2018-08-23 13:46
@lohazo could you ( whenever you find the time to :) ) go into the kube-system namespace and see if any of the pods/deployments in regards to the csi are not booting up correctly ?

**Comment by lohazo** [comment] 2018-08-24 08:19
@peterver seem like everything is running well :)
![1____projects_kubernetes_digitalocean-k8s__zsh_](https://user-images.githubusercontent.com/6048013/44573489-fddcf880-a7b0-11e8-8ebd-3cfdfd6420cf.png)

**Comment by peterver** [comment] 2018-08-24 09:46
okay @fatih looks like this one has nothing to do with #58 then

**Comment by lohazo** [comment] 2018-08-29 16:50
@fatih I upgraded to 0.1.5 but still not work
![1____projects_kubernetes_digitalocean-k8s_echo-server__zsh_](https://user-images.githubusercontent.com/6048013/44802575-4d268d00-abe6-11e8-9cc9-fd5aeefe3fa1.png)

**Comment by akastav** [comment] 2018-08-29 21:37
> I upgraded to 0.1.5 but still not work 

+1

**Comment by fatih** [comment] 2018-09-18 08:59
@lohazo @akastav does this problem still exist? It seems like kubelet cannot talk to the node plugin, which might be the case if you don't setup kubelet to be used in `allow-privileged` mode. 

Please also update to latest `0.2.0` version, if it's still not working, would be happy if you can send me your kubeconfig so I can debug it, here is my email: fatih at digitalocean dot com

**Comment by dzerhusen** [comment] 2018-09-23 19:29
Im facing the same Error. --allow-priviliged is set in api and kubelet.

**Comment by cgroschupp** [comment] 2018-09-28 14:31
I got the same error with `rancheros`, I think it's the same problem as with `coreos`.
https://github.com/rancher/longhorn/issues/198

After adding `extra_binds` to the Kubelet service, everything works.
```
  kubelet: 
    extra_binds: 
      - "/var/lib/kubelet/plugins:/var/lib/kubelet/plugins"
      - "/var/lib/kubelet/pods:/var/lib/kubelet/pods:shared,z"
```

**Comment by Grishy** [comment] 2018-10-06 09:56
> Im facing the same Error. --allow-priviliged is set in api and kubelet.

How did you install --allow-privileged?
Added to /etc/systemd/system / kubelet.service (CentOS7)

**Comment by fatih** [comment] 2018-10-16 11:44
Can anyone here that has still the problem send me their kubeconfig so I can debug it ? (email: fatih at digitalocean dot com). I'm not able to reproduce it, need a way to reproduce it or a cluster I can debug.

**Comment by fatih** [comment] 2018-11-05 09:52
I'm closing this as I don't have any more information to debug this even further. For anyone seeing something this, please make sure to have a reproducible case with the latest version, and better ping me directly (@fatih) and give me the ability to debug your cluster. Having at least a kubeconfig, etc.. is helpful debugging these kind of issues.

**Closed by fatih** 2018-11-05 09:52 UTC
Labels: question

**Comment by alfonmga** [comment] 2019-02-20 16:00
I think this issue is related to `RancherOS` and `CoreOS`. issue: https://github.com/rancher/longhorn/issues/198.

I gave up and switched to `Ubuntu` as OS for my `Rancher` workers and finally everything is working as expected.
