### ISSUE TITLE
Unresolvable Multi-Attach error, after resizing node pools.

### ISSUE THREAD

**Issue by feluxe** [digitalocean/csi-digitalocean#111] opened 2018-11-22 17:10 UTC
### What did you do?

I created a digitalocean (preview) cluster via the DO web interface. In the cluster I installed an app that uses an existing block storage volume with a `PV`/`PVC` config similar to the one in the example [pod-single-existing-volume](https://github.com/digitalocean/csi-digitalocean/tree/master/examples/kubernetes/pod-single-existing-volume).

So far it worked fine.

Then I resized the node pools (delete current pool entirly, add new pool) using the DO web interface. Having done so, the node on which the app was running on and to which the volume was attached to, has been deleted. K8s automatically tried to start the pod on another node, but this isn't working. Pod creation fails with this error:

    Multi-Attach error for volume "nexus-mw-sonatype-nexus-data " Volume is already exclusively attached to one node and can't be attached to another

If I delete the app, everything (including `PV/PVC`) is removed from the cluster, like it should. Even the volume is listed as not being attached to any node in the DO web interface. But when I reinstall the app I keep getting the error, even though the `PV` is shown as being `bound`:

    NAME                           CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                             STORAGECLASS                   REASON   AGE

    nexus-mw-sonatype-nexus-data   10Gi       RWO            Retain           Bound    mw/nexus-mw-sonatype-nexus-data   nexus-mw-sonatype-nexus-data            13m

At this point I'm stuck. I can't find a way to attach the volume to the pod.

### What did you expect to happen?

After the app (incl `PV/PVC`)  was removed from the cluster and the volume was detached, `csi-digitalocean` should be able to attach the volume back to a node.

### Steps to reproduce:

* Create a k8s cluster via the DO web-interface with one node pool.
* Deploy an app that uses an existing DO block storage volume that is configured like in the example: [pod-single-existing-volume](https://github.com/digitalocean/csi-digitalocean/tree/master/examples/kubernetes/pod-single-existing-volume). 
* Wait until the app runs stable with the volume attached to it properly.
* Create a new node pool for the cluster and delete the old node pool entirely (via the DO web-interface).
* Now you are left with a block storage volume that cannot be used with your cluster, because `csi-digitalocean` seems to think it's still attached to the deleted node.

### Configuration:

* CSI Version: `v0.3.1`
* Kubernetes Version: `12.1`
* Cloud provider/framework version: `Digitalocean Kubernetes (Preview)`

**Comment by naarani** [comment] 2018-11-24 11:39
I'm having a similar problems after resize (I had CSI 0.2.0 and I've updated to 0.3.1 manually with kubectl edit)

**Comment by fatih** [comment] 2018-11-27 06:57
Thanks folks for the reports. There were some couple of issues with attachment to dead nodes that were fixed with latest versions of CSI (which I've released yesterday as `v0.4.0`). I'll try to reproduce it today to see how things are in this area and if there is any bug on our side. I'll keep you informed.

**Comment by Azuka** [comment] 2018-12-07 19:52
@fatih, I might be asking in the wrong place, but is the csi plugin updated with DO's kubernetes or does it need to be updated manually?

**Comment by radek-baczynski** [comment] 2018-12-11 16:38
I have same problem with this helm https://github.com/helm/charts/tree/master/stable/traefik 
After installing traefik works but when I add new domain to acme.domains.domainsList and run helm upgrade with new config I got:

`Multi-Attach error for volume "pvc-755581bc-fbde-11e8-b7a2-be5e9cc268b5" Volume is already used by pod(s) traefik-thingie-6db8884ccc-qjsn4`

**Comment by Azuka** [comment] 2018-12-12 00:37
@radek-baczynski, do you want to try deleting the running old pod, or setting your `.spec.strategy` (ie the helm value `deploymentStrategy`) to Recreate? 

That's what I'm using with traefik.

**Comment by murdav** [comment] 2018-12-19 13:14
Did you try to patch the finalizers?

e.g.
kubectl patch pvc <name> -p '{"metadata":{"finalizers":null}}'
kubectl patch pv <ID> -p '{"metadata":{"finalizers":null}}'

and after delete them. I solved like this.
Also https://github.com/rook/rook/issues/1488

**Comment by fatih** [comment] 2019-01-03 15:09
I just tried to reproduce it and was able to see the issue. But this is not a CSI-Digitalocean problem unfortunately. The Driver never gets an attach/detach command and if you check the logs you'll see nothing. It seems like the CSI sub-system is not properly handling these kind of issues. I'm trying to check what we can do here or if there is anything I can do at least.

These are the errors I see from the POD:

```
Events:
  Type     Reason              Age    From                           Message
  ----     ------              ----   ----                           -------
  Normal   Scheduled           3m22s  default-scheduler              Successfully assigned default/my-csi-app-555bfcb94d-nmchm to cranky-brattain-83pu
  Warning  FailedAttachVolume  3m22s  attachdetach-controller        Multi-Attach error for volume "volume-nyc1-01" Volume is already exclusively attached to one node and can't be attached to another
  Warning  FailedMount         78s    kubelet, cranky-brattain-83pu  Unable to mount volumes for pod "my-csi-app-555bfcb94d-nmchm_default(c396a076-0f68-11e9-acf1-82ed94d9aecc)": timeout expired waiting for volumes to attach or mount for pod "default"/"my-csi-app-555bfcb94d-nmchm". list of unmounted volumes=[my-do-volume]. list of unattached volumes=[my-do-volume default-token-l9nfd]
```

I'll comment more on this.

**Comment by radek-baczynski** [comment] 2019-01-03 15:12
change of deploymentStrategy to `Recreate` helped. Thanks

**Comment by fatih** [comment] 2019-01-04 11:58
@radek-baczynski just tried with "Recreate"  and seems like it's really working well. But I waited couple of minutes and the scheduler had time to resolve the issues:

```
Events:
  Type     Reason                  Age                  From                           Message
  ----     ------                  ----                 ----                           -------
  Normal   Scheduled               6m13s                default-scheduler              Successfully assigned default/my-csi-app-555bfcb94d-ws584 to cranky-brattain-83pu
  Warning  FailedAttachVolume      6m12s                attachdetach-controller        Multi-Attach error for volume "volume-nyc1-01" Volume is already exclusively attached to one node and can't be attached to another
  Warning  FailedMount             112s (x2 over 4m9s)  kubelet, cranky-brattain-83pu  Unable to mount volumes for pod "my-csi-app-555bfcb94d-ws584_default(f656145f-1016-11e9-acf1-82ed94d9aecc)": timeout expired waiting for volumes to attach or mount for pod "default"/"my-csi-app-555bfcb94d-ws584". list of unmounted volumes=[my-do-volume]. list of unattached volumes=[my-do-volume default-token-l9nfd]
  Normal   SuccessfulAttachVolume  8s                   attachdetach-controller        AttachVolume.Attach succeeded for volume "volume-nyc1-01"
```

 I wonder if this is the same for `rolling-update` strategy as well. I'll post my findings  here.

**Comment by fatih** [comment] 2019-01-04 12:44
Alright tested it with `RollingUpdate` strategy and confirm that it works well! Here are the events for the pod:

```
Events:
  Type     Reason                  Age                   From                           Message
  ----     ------                  ----                  ----                           -------
  Normal   Scheduled               6m23s                 default-scheduler              Successfully assigned default/my-csi-app-555bfcb94d-7l9x5 to cranky-brattain-83pu
  Warning  FailedAttachVolume      6m23s                 attachdetach-controller        Multi-Attach error for volume "volume-nyc1-01" Volume is already exclusively attached to one node and can't be attached to another
  Warning  FailedMount             2m4s (x2 over 4m20s)  kubelet, cranky-brattain-83pu  Unable to mount volumes for pod "my-csi-app-555bfcb94d-7l9x5_default(341f5f91-101d-11e9-acf1-82ed94d9aecc)": timeout expired waiting for volumes to attach or mount for pod "default"/"my-csi-app-555bfcb94d-7l9x5". list of unmounted volumes=[my-do-volume]. list of unattached volumes=[my-do-volume default-token-l9nfd]
  Normal   SuccessfulAttachVolume  19s                   attachdetach-controller        AttachVolume.Attach succeeded for volume "volume-nyc1-01"
  Normal   Pulling                 10s                   kubelet, cranky-brattain-83pu  pulling image "busybox"
  Normal   Pulled                  10s                   kubelet, cranky-brattain-83pu  Successfully pulled image "busybox"
  Normal   Created                 10s                   kubelet, cranky-brattain-83pu  Created container
  Normal   Started                 10s                   kubelet, cranky-brattain-83pu  Started container
```

The key is that it, it's not instantaneously. We need to wait until the reconciler in Kubernetes is aware of the imperfections and try to reconcile to a correct state. In my tests it reconciled in a good state in around **6 minutes**.

**Comment by travisgroth** [comment] 2019-02-13 11:15
I'm on v0.4.0 and have the same scenario as feluxe.  Here's how I got there:

* Create stateful set app with PVC
* Application is stable with data written to PV
* Unknown scenario began crashlooping app
* Delete crashlooping pod
* Get PV warnings:

```
Warning  FailedMount  1m (x11 over 7m)  kubelet, charming-austin-8yz0  MountVolume.WaitForAttach failed for volume "pvc-1c06f5ec-1800-11e9-a645-5af0d80f33cc" : volume attachment is being deleted

Warning  FailedMount  1m (x3 over 5m)   kubelet, charming-austin-8yz0  Unable to mount volumes for pod "prometheus-prometheus-prometheus-oper-prometheus-0_prometheus(0cc769e6-2f2a-11e9-a3f3-1e02303657d9)": timeout expired waiting for volumes to attach or mount for pod "prometheus"/"prometheus-prometheus-prometheus-oper-prometheus-0". list of unmounted volumes=[prometheus-prometheus-prometheus-oper-prometheus-db]. list of unattached volumes=[prometheus-prometheus-prometheus-oper-prometheus-db config config-out prometheus-prometheus-prometheus-oper-prometheus-rulefiles-0 prometheus-prometheus-oper-prometheus-token-rd6s5]
```
* Wait for 5-10 minutes
* Recycle node via DO control panel (creates new node, deletes old)
* New, slightly different warning:

```
  Warning  FailedAttachVolume  7m                attachdetach-controller        Multi-Attach error for volume "pvc-1c06f5ec-1800-11e9-a645-5af0d80f33cc" Volume is already exclusively attached to one node and can't be attached to another

Warning  FailedMount         39s (x3 over 5m)  kubelet, charming-austin-unyu  Unable to mount volumes for pod "prometheus-prometheus-prometheus-oper-prometheus-0_prometheus(8d61cc70-2f7f-11e9-a3f3-1e02303657d9)": timeout expired waiting for volumes to attach or mount for pod "prometheus"/"prometheus-prometheus-prometheus-oper-prometheus-0". list of unmounted volumes=[prometheus-prometheus-prometheus-oper-prometheus-db]. list of unattached volumes=[prometheus-prometheus-prometheus-oper-prometheus-db config config-out prometheus-prometheus-prometheus-oper-prometheus-rulefiles-0 prometheus-prometheus-oper-prometheus-token-rd6s5]
```
This continues whether the volume is attached to the new node or not.  How do I resolve this?

**Comment by twogood** [comment] 2019-02-24 20:16
Thank you @Azuka and @radek-baczynski , it seems I could solve this for traefik (installed with helm) by changing strategy to `Recreate`.

**Comment by timoreimann** [comment] 2019-11-02 11:17
Newer releases of the CSI plugin address a few bugs, most notably one about failure to detach due to a bug in the external-attacher side car. Please update to the latest possible version and file a new issue if the problem continues to happen.

Thank you!

**Closed by timoreimann** 2019-11-02 11:17 UTC
