### ISSUE TITLE
DO provisioned volume is not formatted to its maximum free space

### ISSUE THREAD

**Issue by chatsatourian** [digitalocean/csi-digitalocean#175] opened 2019-07-19 11:40 UTC
### What did you do?

- Created 3 volumes with doctl.
- Created 3 persistent volumes with volume handles referring to the previously created volumes.
- Created 3 persistent volume claims for the 3 persistent volumes.
- Created a dummy headless service for the stateful set.
- Created a stateful set with 3 replicas and a volume claim template.

### What did you expect to happen?

I expected a stateful set with 3 replicas and a volume with the requested size attached on each. Unfortunately, the size available was approximately 380M.

I managed to resize one of the affected volumes with resize2fs while the volume was detached. In order to detach the volume I killed the pod that was using it. When the pod was recreated, the available size was the expected. Since multiple volumes were affected by this issue every time I reproduced it, I continued the troubleshooting to find something more suitable.

The do-csi-plugin checks if the volume is formatted with the mounter.IsFormatted function. The problem is that this function uses blkid to simply check if there is a record for the volume in question. It does not seem to check the file system or the size requested by the user. In my case the volume is formatted to EXT4 but for some reason the size is not maxed out. Since there is a record for the volume, the function returns true and the do-csi-plugin skips formatting the volume.

I pushed an image where I disabled the mounter.IsFormatted function and forced the formatting of the volume. The next problem I encountered was that one of the nodes was of different type, s-4vcpu-8gb instead of s-2vcpu-4gb like the rest, and the volume was not detached so that the do-csi-plugin could format it.

### Configuration:

```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: busybox-hs
  namespace: test
  labels:
    application: busybox
spec:
  clusterIP: None
  selector:
    application: busybox
  ports:
    - port: 80
```
```yaml
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-busybox-0
  namespace: test
spec:
  storageClassName: do-block-storage
  volumeName: test-busybox-0-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      name: busybox
      do-availability-zone: fra1

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-busybox-1
  namespace: test
spec:
  storageClassName: do-block-storage
  volumeName: test-busybox-1-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      name: busybox
      do-availability-zone: fra1

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-busybox-2
  namespace: test
spec:
  storageClassName: do-block-storage
  volumeName: test-busybox-2-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      name: busybox
      do-availability-zone: fra1
```
```yaml
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-busybox-0-pv
  annotations:
    pv.kubernetes.io/provisioned-by: dobs.csi.digitalocean.com
  labels:
    name: busybox
    do-availability-zone: fra1
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: do-block-storage
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    name: data-busybox-0
    namespace: test
  csi:
    driver: dobs.csi.digitalocean.com
    fsType: ext4
    volumeHandle: 6801f6fd-aa0a-11e9-9bfb-0a58ac14d11d
    volumeAttributes:
      com.digitalocean.csi/noformat: "true"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-busybox-1-pv
  annotations:
    pv.kubernetes.io/provisioned-by: dobs.csi.digitalocean.com
  labels:
    name: busybox
    do-availability-zone: fra1
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: do-block-storage
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    name: data-busybox-1
    namespace: test
  csi:
    driver: dobs.csi.digitalocean.com
    fsType: ext4
    volumeHandle: 6b6aef28-aa0a-11e9-babe-0a58ac14d0b7
    volumeAttributes:
      com.digitalocean.csi/noformat: "true"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-busybox-2-pv
  annotations:
    pv.kubernetes.io/provisioned-by: dobs.csi.digitalocean.com
  labels:
    name: busybox
    do-availability-zone: fra1
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: do-block-storage
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    name: data-busybox-2
    namespace: test
  csi:
    driver: dobs.csi.digitalocean.com
    fsType: ext4
    volumeHandle: 6f7b9d03-aa0a-11e9-9bfb-0a58ac14d11d
    volumeAttributes:
      com.digitalocean.csi/noformat: "true"
```
```yaml
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: busybox
  namespace: test
  labels:
    application: busybox
spec:
  podManagementPolicy: Parallel
  replicas: 3
  serviceName: busybox-hs
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      application: busybox
  template:
    metadata:
      labels:
        application: busybox
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: environment
                    operator: In
                    values:
                      - test
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: kubernetes.io/hostname
              labelSelector:
                matchExpressions:
                  - key: application
                    operator: In
                    values:
                      - busybox
      containers:
        - name: ubuntu
          image: ubuntu:19.04
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: data
              mountPath: /var/lib/busybox
          resources:
            requests:
              cpu: 75m
              memory: 128Mi
            limits:
              cpu: 75m
              memory: 128Mi
          command: ["/bin/sh", "-c"]
          args: ["sleep 36000"]
  volumeClaimTemplates:
    - metadata:
        name: data
        namespace: test
        labels:
          application: busybox
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi

```

* CSI Version: v1.1.0 updated to v1.1.1

* Kubernetes Version: v1.14.1

* Cloud provider: DigitalOcean

**Comment by adamwg** [comment] 2019-09-17 19:30
Hi @chatsatourian - thanks for reporting this.

The issue is that DO pre-formatted volumes (volumes created via the API/UI with a format) rely on udev rules on the droplet to resize the filesystem the first time it's attached. DOKS worker droplets don't have these udev rules installed, so the filesystem never gets resized. I don't think we want to include the udev rules we use for normal droplets in DOKS droplets (since they also configure automount for formatted volumes) but we may be able to include rules to do just the resize in a future DOKS release.

In the meantime, a workaround is to not pre-create volumes for use with CSI. The CSI driver will create volumes for you and format them correctly to the requested size if you create just a PVC with the `do-block-storage` storage class - no need to provide a PV manifest. Is there a specific use-case you have that requires creating an empty volume outside of CSI? The usual reason for creating a volume manually rather than letting the CSI driver do it is to pre-load some data onto the filesystem, but it sounds like you're not doing that in this case.

**Comment by chatsatourian** [comment] 2019-09-18 06:48
Hi @adamwg,

The configuration I provided was a simple example to reproduce the issue. If I remove the PV and PVC resources, the DO generated PVs will have the following format, pvc-{UUID}. By providing the PV and PVC resources, I have to create the volumes beforehand and get their volume handle UUIDs, though I am able to reflect the service name and stateful set ordinal of the pod through their names.

**Comment by adamwg** [comment] 2019-09-18 14:13
@chatsatourian I see - that makes sense. For your use-case, pre-creating a volume without a format should work. The CSI driver will format the volume if no filesystem is detected. You can do this through the DO control panel by selecting `Manually Format & Mount` in the create dialog, or by omitting the `filesystem_type` field from the request if using the API.

That said, I will also look at whether we can resize on attach either via udev rules (like we do for volumes attached to non-DOKS droplets) or in the CSI driver. The CSI node driver doesn't receive the requested size as a parameter when a volume is attached, but I think we can safely assume that the filesystem should fill the volume. I lean toward doing the resize via the CSI driver, since it would work for any cluster using it, not just DOKS, and we can provide an override via annotations for users who may want to intentionally create a volume with a smaller filesystem.

**Comment by timoreimann** [comment] 2019-12-01 19:02
The latest (yet unreleased) version of our CSI driver supports volume expansion which also takes care of resizing the file system as needed. It's another workaround, albeit one somewhat less involved.

It might be worth checking the spec if it covers file system resizing to the target size even without triggering the expansion functionality explicitly. FWIW, the proper tooling (resize2fs) is already shipped with our driver container.

That being said, I'm not sure I fully understood what the use case is. Pre-creating a volume and putting the PV / PVC objects in place is quite a hassle, so I'm curious if this is something people intend to do on purpose, or more of a theoretical case. If the former, then we can continue to explore ways to address the problem automatically. If the latter, then a warning note on the README might be good enough.

Very open to get more input on this one.

**Comment by timoreimann** [comment] 2022-08-08 12:24
Closing out since we're lacking further feedback. Happy to re-open if there's desire for that from users.

**Closed by timoreimann** 2022-08-08 12:24 UTC
