### ISSUE TITLE
Something wrong with roles and accesses

### ISSUE THREAD

**Issue by dbogatov** [digitalocean/csi-digitalocean#90] opened 2018-10-15 06:31 UTC
### What did you do? (required. The issue will be **closed** when not provided.)

Followed README instructions.

### What did you expect to happen?

Volume provisioning when PVC is created.

## What happened?

Nothing got provisioned, with no apparent error.

The clue is in the provisioner container log:

```
E1015 06:09:56.572929       1 reflector.go:205] github.com/kubernetes-csi/external-provisioner/vendor/github.com/kubernetes-incubator/external-storage/lib/controller/controller.go:497: Failed to list *v1.PersistentVolume: persistentvolumes is forbidden: User "system:serviceaccount:kube-system:csi-do-controller-sa" cannot list persistentvolumes at the cluster scope: [clusterrole.rbac.authorization.k8s.io "system:csi-external-provisioner" not found, clusterrole.rbac.authorization.k8s.io "system:csi-external-attacher" not found]
```

### Configuration (**MUST** fill this out):

Dump is too big for gist.
Let me know if you need it, I will find a way to host it.

**Comment by fatih** [comment] 2018-10-15 07:08
@dbogatov which version do you use and how did you installed it?

**Comment by fatih** [comment] 2018-10-15 07:09
@dbogatov also please provide the k8s version you're using

**Comment by dbogatov** [comment] 2018-10-15 07:09
```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-28T15:18:13Z", GoVersion:"go1.11", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1", GitCommit:"3a1c9449a956b6026f075fa3134ff92f7d55f812", GitTreeState:"clean", BuildDate:"2018-01-04T11:40:06Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```

Installed with Typhoon.

**Comment by fatih** [comment] 2018-10-15 07:14
Alright, so the issue is that you're using an old Kubernetes version. The ClusterRoles were added in 1.10.5 (https://github.com/kubernetes/kubernetes/pull/65073) so that's the minimum version we're require (also written in our README: https://github.com/digitalocean/csi-digitalocean#installing-to-kubernetes)

You're using `v1.9.1` which is old compared to what we require. Closing this now. Feel free to open another issue if you encounter something else.

**Closed by fatih** 2018-10-15 07:14 UTC
